version: "3"

services:
  webapp:
    image: h99www/today-react-server
    ports:
      - "80:80"
    depends_on:
      - app
  app:
    image: h99www/today-express-server
    ports:
      - "8888:8888"